name: DHMO
description: Dihydrogen Monoxide Awareness
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.64.1 <3.0.0'

dependencies:
  angular: ^5.0.0-beta

# #docregion dev_dependencies, build-dependencies
dev_dependencies:
  # #enddocregion build-dependencies
  angular_test: ^2.0.0-beta
  # #docregion build-dependencies
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  # #enddocregion build-dependencies
  test: ^1.0.0
# #enddocregion dev_dependencies
